### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TupleProxy'

### ISSUE THREAD

**Issue by emucaki** [QBRC/PIPE-CLIP#9]
I have finally installed all dependencies (including python packages pybedtools and ghmm), and I get the following error when attempting to run the program:

>python pipeclip.py -i ERR_TopHat_Aligned.bam -o ERR-NoRepeatRemoval -c 3 -l 25 -m 2 -r 0 -M 0.05 -C 0.05 -s hg19

Traceback (most recent call last):
  File "pipeclip.py", line 13, in <module>
    from lib import *
  File "/project/6000237/emucaki/RNPS1-FASTQ/PIPE-CLIP-master/lib/__init__.py", line 2, in <module>
    import Alignment
  File "/project/6000237/emucaki/RNPS1-FASTQ/PIPE-CLIP-master/lib/Alignment.py", line 6, in <module>
    import Enrich
  File "/project/6000237/emucaki/RNPS1-FASTQ/PIPE-CLIP-master/lib/Enrich.py", line 15, in <module>
    from pysam import *
AttributeError: 'module' object has no attribute 'TupleProxy'

Any help would be most appreciated.

**Comment by jalalsiddiqui** [comment]
I am having the same error with this.  I would appreciate any help that I can get.

**Comment by jalalsiddiqui** [comment]
I also have made an issue with pysam if this can help

https://github.com/pysam-developers/pysam/issues/809

**Comment by Missxiang** [comment]
I am having the same error with this, I would appreciate any help that I can get,too
